### PR TITLE
Annual report

### PR DESCRIPTION
**Pull request by fontofonto**
- merge and resolve the conflicts with master
- change the og image from the newsletter image to og-image.jpg to meet the standard of Open Graph
- fix the styles in RegionsWrapper

### CODE REVIEW

**Comment by fontofonto** [comment]
@chochihim

**Review by chochihim — COMMENTED** [review]
The use of `gatsby-plugin-open-graph-images` looks unnecessary. Can you confirm?

**Comment by fontofonto** [comment]
> 

Yes, I think ```gatsby-plugin-open-graph-images``` can be removed from the project dependency.

**Review by chochihim — CHANGES_REQUESTED** [review]
Please also remove it from `gatsby-config.js`

**Pull request merged**
